"""Canonical product identity. Never derived from the host or development tools."""
PRODUCT = "ACHERON"
DESCRIPTION = "Binary Analysis & Decompilation Platform"
CREATOR = "cirrune"
ATTRIBUTION = "Created by cirrune"
COPYRIGHT = "Copyright © cirrune"
CHARON_PRODUCT = "ACHERON // CHARON"
CHARON_DESCRIPTION = "AI-Assisted Binary Investigation Environment"
AIR_NAME = "Acheron Intermediate Representation"
